### ISSUE TITLE
Update display via _thread without flicker?

### ISSUE THREAD

**Issue by danielmader** [benjohnemmett/Hub75MicroPython#4]
In a simple clock application, I am counting up seconds with a timer and convert this into a timestamp. (Every once in a while, I am also checking for the correct time via NTP.)
The timestamp string is then converted to a series of character images.
This approach seems to work, but the clear_dirty_bytes() call causes a flicker.
The hub75spi.display_data() is running constantly in a separate thread all the time.
Is there anything I can do to reduce this short flickering every second?

**Comment by benjohnemmett** [comment]
A flicker every second would definitely be irritating on a clock. The issue here is that the LEDs are only illuminated during the display_data() call. So any processing outside of this call adds to blank time between frames. Even using separate threads won't help here because in python the threads are all executed on the same core. 

You might try to synchronize the time less often. Maybe once a minute/hour/day, depending on how much the internal clock drifts and how often you can tolerate a flicker on the display. If the drift is significant, you could also try using a real-time clock module to keep a more accurate local time and then synchronize that to network time less often. Or you could add a second ESP32 that receives time from NTP and then sends over accurate time to the ESP32 driving the LED matrix. I'm just spitballing now. I'm not sure what approach would work best for you, but I don't see a way to improve the library to reduce the flicker.

**Comment by danielmader** [comment]
I am synchronizing only every 12 hours. This is not the problem. I am seeing this flicker every second when I update the graphics on the display.
Here's a simplified code to reproduce:

```
import hub75
import matrixdata
from logo import logo

import _thread
import time
from machine import Timer
#import uasyncio

ROW_SIZE = 32
COL_SIZE = 64

config = hub75.Hub75SpiConfiguration()
##-----------------------------------------------------------------------------
## row select pins
config.line_select_a_pin_number = 15
config.line_select_b_pin_number = 2
config.line_select_c_pin_number = 4
config.line_select_d_pin_number = 16
config.line_select_e_pin_number = 12
## color data pins
config.red1_pin_number = 32
config.green1_pin_number = 33
config.blue1_pin_number = 25
config.red2_pin_number = 26
config.green2_pin_number = 27
config.blue2_pin_number = 14
## logic pins
config.clock_pin_number = 18
config.latch_pin_number = 5
config.output_enable_pin_number = 17  # active low
config.spi_miso_pin_number = 13  # not connected
## misc
config.illumination_time_microseconds = 1
##-----------------------------------------------------------------------------
matrix = matrixdata.MatrixData(ROW_SIZE, COL_SIZE)
hub75spi = hub75.Hub75Spi(matrix, config)

# Show Python Logo
matrix.set_pixels(0, 16, logo)
for i in range(100):
    hub75spi.display_data()

# Show objects
square = [
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7],
    [1,1,2,2,3,3,4,4,5,5,6,6,7,7]]

##-----------------------------------------------------------------------------
## run permanent display thread
def displayThread():
    while True:
        hub75spi.display_data()
_thread.start_new_thread(displayThread, ())
        
##-----------------------------------------------------------------------------
## run timed thread
def clocktick(timer):
    matrix.clear_dirty_bytes()
    matrix.set_pixels(10,10, square)
tim = Timer(-1)
tim.init(period=1000, mode=Timer.PERIODIC, callback=clocktick)
```

**Comment by benjohnemmett** [comment]
I see what you mean now. The clear_dirty_bytes() call seems to be the culprit. The issue isn't that it's threaded though, it's just that when you are using a larger pixel area it will take longer to clear the dirty pixels from memory, which leaves the panel blank for longer. I'll see if I can find a way to improve performance on clear_dirty_bytes(). 

You might try writing custom code to only clear out the pixels that you need to (for example, just clear the seconds but not the minute or hour).

You could also try to clear the entire memory buffer instead of just the dirty pixels. I'm guessing that will probably also cause a flicker though.

I think that driving Hub75 is pushing the limits of micropython on the ESP32. Hopefully we can squeeze enough performance out of it to get your project where you want it. It sounds like you are pretty close.

**Comment by danielmader** [comment]
The whale is not working for me (just a blue-white square from top to bottom shifting left and right)., I will see if I can work it out. 

I've experimented with a faster way to reset dirty pixels. Looping through rows and columns seems slower to me than just starting over again. Unfortunately, this had no visible effect, neither negative nor positive.

```
    def clear_all_bytes(self):
        '''
        Reset all pixels.

        Returns
        -------
        None.
        '''
        # works
        self.red_matrix_data = [bytearray(self.col_bytes) for x in range(self.row_size)]
        self.green_matrix_data = [bytearray(self.col_bytes) for x in range(self.row_size)]
        self.blue_matrix_data = [bytearray(self.col_bytes) for x in range(self.row_size)]
        # does not work but should be the same ?!
        # self.red_matrix_data = [bytearray(self.col_bytes)] * self.row_size
        # self.green_matrix_data = [bytearray(self.col_bytes)] * self.row_size
        # self.blue_matrix_data = [bytearray(self.col_bytes)] * self.row_size

        self.dirty_bytes_array = []
```

I have also included docstrings to the matrixdata.py module and cleaned up the indentation of logo.py and planets.py. Plus, we need some corrections to the Readme.md. Let's see if I can work it out with a pull request.

As for my clock app, I've now removed the seconds and only show hours and minutes. This is OK for now, and wife is happy. I am planning to publish the code after some clean-up.

**Comment by benjohnemmett** [comment]
That's great news. I'm glad you have it working. I think that clearing only the dirty bytes is advantageous when there are only a small number of pixels used. For example, I think that the earth bouncing only uses ~20 bytes. When more of the bytes have been modified then at some point it's probably faster just to clear them all. 

I looked over the pull request and I like the addition of clear_all_bytes(). I also appreciate the formatting cleanup & added docstrings. I left a few comments to address before I pull it in.

**Comment by benjohnemmett** [comment]
I pushed one last update that may help. I added a flag to the MatrixData constructor which can be used to disable recording the dirty bytes. This will reduce the amount of time required to set the pixels when clear_dirty_bytes() isn't being used.

I also switched tracking dirty bytes from using a list to using a set to avoid adding duplicate byte indices. I thought this would speed things up, but I haven't seen any improvement from it as far as reducing flicker when displaying a large image. I'm sure it is making more efficient use of memory though.

I will go ahead & close out this issue. I don't think there is an issue in the code causing the flicker, it's just that processing more pixels takes more time which causes a larger blanking time between refresh cycles.
